services:
  hugo:
    image: jakejarvis/hugo-extended:0.124.1
    ports:
      - 1313:1313
    volumes:
      - ./:/src
    user: "${UID}:${GID}"
    command: server --buildDrafts --buildFuture --bind 0.0.0.0
