[build]
command = "hugo --gc --minify -b $DEPLOY_URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.101.0"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"