#!/bin/sh

create_post() {
  title=$(echo "$@" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
  UID=$(id -u) GID=$(id -g) docker compose exec hugo hugo new posts/"$title"/index.md
}

main() {
  echo "Please enter the title of the post"
  read -r title
  create_post "$title"
  exit 0
}

main
